### ISSUE TITLE
Fix using from PATH environment

### ISSUE THREAD

**Issue by hakatu** [superzeldalink/quartus-install#1]
To use from terminal use `nano ~/.bashrc` or your environment setting path, add this to the end of the file.

`export PATH="$PATH:/$userpath/quartus/bin/:/$userpath/questa_fse/bin/"`
`export LM_LICENSE_FILE=/$pathtolicensefile/License_Questa.dat`

then `source ~/.bashrc`

Quartus should run fine now, QuestaSim can try to access linux_aarch64 and fail out.

do `nano /questa_fse/vco`

Change the architecture path to:

>        # On Linux, default to 32 bit unless MTI_VCO_MODE is set
> 	  # except for Visualizer where we invoke 64-bit version by default
> 	  if [ "$mode" = "" ] ; then
> 		  if ( [ "$cmd" = "visualizer" -o "$cmd" = "vis" ]) \
> 		  && ( [ -x "$dir/linux_x86_64/visualizer" ] ) ; then
> 			  mode="64";
> 		  elif ( [ -x "$dir/linux/vsim" -o -x "$dir/linuxpe/vsim" ] ) \
> 		  &&   ( [ "$umach" != "aarch64" ] ); then
> 			  mode="32";
> 		  fi
> 	  fi
> 
> 	  # If IA-64 or X86-64 architecture and machine-specific vsim is not
> 	  # installed but linux vsim is available, use linux platform.
> 	  # Otherwise use machine-specific platform.
> 	  #
> 	  if [ "$mode" != "32"  ]            \
>       && (  [ "$umach" = "ia64" ]         \
> 		 || [ "$umach" = "x86_64" ]       \
>          || [ "$umach" = "aarch64" ] )    \
>       && (  [ "$mode" = "64" ]            \
>          || [ -x "$dir/linux_x86_64/vsim" ] \
>          || [ ! -x "$dir/linux/vsim" ] ) ; then
> 		vco="linux_x86_64"
>       else
> 		vco="linux"
> 		if [ ! -x "$dir/$vco/vsim" -a -x "$dir/linuxpe/vsim" ]; then
> 			vco="linux_x86_64"
> 		fi
>       fi

Should fix the issue

**Comment by superzeldalink** [comment]
Thank you for your solution.

The updated scripts will add Quartus and Questa to PATH after the installation, and apply necessary patches to the Questa's `vco` file for aarch64 compatibility. The `quartus-install.py` will automatically apply the post-installation scripts, after installing all the components (`vco` patch only runs when you install Questa along with Quartus).

You can manually execute them using `foreign-post.sh` and `foreign-post-questa.sh` scripts within the `foreign` folder.

Best regards!
